language: node_js
node_js:
- '8'
stages:
- test
- name: deploy
  if: "(NOT type IN (pull_request)) AND (branch = master)"
install:
- make install
jobs:
  include:
  - stage: test
    script: make test
  - stage: deploy
    script: make
    deploy:
      provider: s3
      access_key_id: $AWS_KEY
      secret_access_key: $AWS_SECRET
      bucket: bhp-react-timeline-9k
      local-dir: dist
      acl: public_read
      skip_cleanup: true
      region: ap-southeast-2
      on:
        repo: lilfolr/react-timeline-9000
        branch: master
cache:
  yarn: true
  directories:
  - node_modules
env:
  global:
  - secure: C4dkf2JvEd5T5J/HfIZCgnOc6IGoPEh+BXQENv8p8wyk9k1Yv7MsOBwdOs/HgsKzhOsznABEoUpc9I5669541xayt1+K0Lr5BQg5Ak+OI90FnCP8Me/5TQSoARlaCchGZplXJfqzPt0L9/SdcRPGhiU7v6WKzUkAPE9Q2bldllCSPuBc1GvWg7ak3ujKjx+lt+vcziu0nSFkVIvQhB3LNPBTU9g0b6WhsPCX86H+MC7UQ5vVHsi20FEX8vtS3AP46KbSuAQFVHdSKbQ10L26CV/KhFmfhOY/Moq+XcjGvKTWayoZ2Djv3LqsIfywhTKlirnz16ICmyvwhEDpt/GZqJKSDVTYcZL7Mql3DiHkRwx/DYWWufaenkxBUss8+Incs/6f5cBoUKt1XsbEc9LIbhiOOxRqzkU7JVb9OHSabZ3jI73ZJ9OtFhZxJKnSieluDbttiQ2yfUIEh2XvtKhMeQPQEDmwLp7WXi/NSaxQpkZIjU6hPLSjdUIrlPdonkiyVLGnwd1kjdishLMK+BxM9dKI3Q8aOSdEnYHNWy0SPXrsJb+6daZCJVzFh6YHlebRBD/5LnS0a4U2AP7iqckSqIEma7cyZxscSWcCUtBx5MVWKgBUdBv7yTbnSQ/ufBnWKt1l0v+1gr/dfUnTTz8O6LL82loQF8Sme4qcpKtnOb4=
  - secure: Vylt+ak2jP2g2zq/dq9AUju3F4Kpaf/F+1TmCznwKV9sP0b/y8iwovL+pbRXbd4VsKtpubtccU5xGOrVVWZ0veESjif6WrRushGwWWmh948N4kF64iiaA6mz7ji3HHleaHeMsuTWqt+1adAZrV1W3tQ5dpm6d72pYx14V4oi1t0dfhqBVEgeMBrS+l6ZUnJXi321pPQcSKPbYLkgP4Ro39ydX131c6cY7uuRjKERvzFl83GZNcjB9T2RI9rD278zRJkpZmJWixdfpsHOClhLacXpP85pvGAu+/PfvnjOY7+7ol+/uxkEUA16Qx5rNLWAN6nC4sUAvHkC3uLlhIGznZgH5j7ThjezTcI2e3JKcCCNgnWeWg5vouwUSpGbD8/Zuo0xE89M3j4gPhQIpOQgjMIUm+1d3SKWHkd2P+3KpWoteIyA1Dh5mc2kF5G86x7cOvrfiv+UeXp20HyB9VP13X24L9+KkO5UEQONsQjlL63vnRWgRH3KLcAxjfF0GPilVPtthLuZFdq5jlkO8F+iHMRo7YgpF4DD/ZWzb5d0PDS75xfEhYP1dLXSvRaR/L055nWOjJHO9YHZww1wgYw+wEnxtunFAo8D9oT/fhRBznnHbgMnJ619C3N8r8NafhZbZ5coIKDhG1DhUwNuimCzujKfHVzr7TzHMkcThflxJj0=
