language: node_js
node_js:
- '8'
stages:
  - test
  - name: deploy
    if: (NOT type IN (pull_request)) AND (branch = master)
install:
- make install
jobs:
  include:
    - stage: test
      script: make test
    - stage: deploy
      script: make
      deploy:
        provider: s3
        access_key_id: $AWS_KEY
        secret_access_key: $AWS_AWS_SECREY
        bucket: bhp-react-timeline-9k
        local-dir: dist
        acl: public_read
        skip_cleanup: true
        region: ap-southeast-2
        on:
          repo: lilfolr/react-timeline-9000
          branch: master


cache:
  yarn: true
  directories:
  - node_modules
