language: node_js
node_js:
- '8'
stages:
- test
- name: deploy
  if: "(NOT type IN (pull_request)) AND (branch = master)"
install:
- make install
jobs:
  include:
  - stage: test
    script: make test
  - stage: deploy
    script: make
    deploy:
      provider: s3
      access_key_id:
        secure: rtOXg64h10Yy5EjarsuLYFvkdQWTdEQNwXLas65I6LM+XaVCFgCVcqQ1DC90DUrGGGAH04BF8MSLKsbHLRBkl48Zo3c2N5OfZS944ahJSrgFJSR9QO7GnVEx/OG2wrEx6pck+AFTcirfb29rBZ1a6kszG3hMqVDlyFfTuL/C3FokCEEbxhEVFWhSUAIAOxRY263b3tW2xTdP/LEZWAmoskZ/HmfuknNQ85waQkrgnsqaxfYgUkFzxSu06Za02SF2OGBmvtmchX2IEL1jqrQ4bcAjh74XWCRisaMHFRpwLZnFlSx1Q5CtGfHtDcXckVWsBds/B2Ip0yrwMCDiYjlKnaQkoOcWOi7ChyiOZDE/fgyejxbe9P7mElwDJwEhISRxncUZuez5kIbYSzDGXe0LbdeeTesnaTCOeIBZ53zKMBDHisZx4fsvbggJXky99O/LYLWfgnzXwNF1wSWUirSg5Bm/gQXPZ2yq2SCOAKl0ZrhqgwPOQTA8y5ZIiuzr8gOIvCbhObF3DOYBtSUTy0SL/NYxyxb+lZBJkuXpreKz3Iwf/gxJw29yr5bJsct/H4jTqqZW2fO6lFusXLxeeLZz6LAPOZdTowpo/WN2E88TxVILx9ziMuMHDvvx4woWc9ZMjE526cN94YyA0BUv4m66MBHBZYQzRUb1XlKRpx9SEf8=
      secret_access_key:
        secure: m+KyoT7iZHk3YkFKcHjcHHTCm9OlVxcupdoq8m70fSTcdOMA6QvKMLGkAFei9f4da58vMDkqeK6Fcvcl17RxTdjoj29oKdL626QA5d61Ky8J12DYGfLNCMOfHhxUJmdSyCExDZVvoLC3WJwwBeYLR2Pxeefn2MJrzC30vIyfKRGycPTbesBXmF1I1qQkznxWghuq9XPDSG8yhqY/oD9vYX2Scc2Y7L91SGtQfZehq8flwmqtXdddwJ1DYljBmBS0xCaGSStPee3x5QycSQYDgJqri4LZ3WUd+xZj0VuZvIFO5x7OqV6vNOByMPssMDuTRqHTKMM9l9uQMQ1qLW7fv//XiGxZGdcHNd7Ulr+jVl9g6UIxSLCujPLHOpYp+RmHT+rmS7d7W2LDy/oF28gBlDGAzTwRd7Q0QNhxcFSXUTV3HjYbW/EX+EkXqK4UeeLn7x4j5LbAHzX1rsGx8Ct21n2ycdzv3Vb4NA8AHBmU8440k0BVFupoced8bV6om9rNZ1xf4wj6uRiojQqSL9lXbcBaJcHNTZYZ+y0AlCgudRBA+JkrjJEw8Te8GXrMMx/QBeN3IQAVk8HDrQvhg0/wziTZrS90ldEFnZ5Bkgy9F0IZOHSkHhWx7PXXNOdePkiXu3G0GoaMZu34mDHXFf6DQ61VduMonaiB8Rz0YDN4XNA=
      bucket: bhp-react-timeline-9k
      local-dir: dist
      acl: public_read
      skip_cleanup: true
      region: ap-southeast-2
      on:
        repo: lilfolr/react-timeline-9000
        branch: master
cache:
  yarn: true
  directories:
  - node_modules
